### ISSUE TITLE
how to encrypt using public key. I have java code.

### ISSUE THREAD

**Issue by bajrang8955** [KevinBusse/PBEWithMD5AndDES#4]
Hi,
I have some java code and its using this same php type encryption. 
I want the java encryption in php. I can give you java code and ready to pay for this.
Please reply me.
bajrang8955@gmail.com
Thanks.

**Comment by KevinBusse** [comment]
Unfortunately the code would require a refactoring to use openssl, since it is no longer supported.

And at the moment it only supports passphrases.
